# Generated by Django 4.1.4 on 2022-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=500, verbose_name='Фото товара'),
        ),
    ]
