# Generated by Django 4.1.4 on 2022-12-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='map_coordinates2',
            field=models.CharField(default=1, max_length=255, verbose_name='Координаты на карте'),
            preserve_default=False,
        ),
    ]
